package test.spark

import java.util.Random

import scala.io.AnsiColor

package object twitter {

  val ids= Array[String]( 
    "AVfgqDH8Tt9xTVODWX36",
    "AVfgqDJgTt9xTVODWX3_",
    "AVfgqDLzTt9xTVODWX4G",
    "AVfgqDMcTt9xTVODWX4I",
    "AVfgqDPPTt9xTVODWX4Q",
    "AVfgqDPkTt9xTVODWX4R",
    "AVfgqDP5Tt9xTVODWX4S",
    "AVfgqDQOTt9xTVODWX4T",
    "AVfgqDQkTt9xTVODWX4U",
    "AVfgqDS4Tt9xTVODWX4a",
    "AVfgqDUhTt9xTVODWX4e",
    "AVfgqDVUTt9xTVODWX4g",
    "AVfgqDWFTt9xTVODWX4i",
    "AVfgqDa0Tt9xTVODWX4v",
    "AVfgqDbmTt9xTVODWX4x",
    "AVfgqDb5Tt9xTVODWX4y",
    "AVfgqDdSTt9xTVODWX42",
    "AVfgqDgbTt9xTVODWX4_",
    "AVfgqDheTt9xTVODWX5C",
    "AVfgqDkNTt9xTVODWX5J",
    "AVfgqDnFTt9xTVODWX5Q",
    "AVfgqDqFTt9xTVODWX5Z",
    "AVfgqDqYTt9xTVODWX5a",
    "AVfgqDsuTt9xTVODWX5h",
    "AVfgqDteTt9xTVODWX5j",
    "AVfgqDw2Tt9xTVODWX5t",
    "AVfgqD4LTt9xTVODWX5_",
    "AVfgqD5LTt9xTVODWX6C",
    "AVfgqD7yTt9xTVODWX6J",
    "AVfgqD90Tt9xTVODWX6P",
    "AVfgqD-fTt9xTVODWX6R",
    "AVfgqEAzTt9xTVODWX6Y",
    "AVfgqEGpTt9xTVODWX6n",
    "AVfgqEH6Tt9xTVODWX6q",
    "AVfgqEJrTt9xTVODWX6v",
    "AVfgqEN5Tt9xTVODWX68",
    "AVfgqEO-Tt9xTVODWX6_",
    "AVfgqER9Tt9xTVODWX7I",
    "AVfgqEUgTt9xTVODWX7P",
    "AVfgqEXpTt9xTVODWX7X",
    "AVfgqEZWTt9xTVODWX7c",
    "AVfgqEbRTt9xTVODWX7i",
    "AVfgqEbkTt9xTVODWX7j",
    "AVfgqEb4Tt9xTVODWX7k",
    "AVfgqEc2Tt9xTVODWX7n",
    "AVfgqEdTTt9xTVODWX7o",
    "AVfgqEfiTt9xTVODWX7v",
    "AVfgqEf2Tt9xTVODWX7w",
    "AVfgqDGRTt9xTVODWX32",
    "AVfgqDHRTt9xTVODWX34",
    "AVfgqDIjTt9xTVODWX38",
    "AVfgqDI5Tt9xTVODWX39",
    "AVfgqDKKTt9xTVODWX4B",
    "AVfgqDNHTt9xTVODWX4K",
    "AVfgqDRSTt9xTVODWX4W",
    "AVfgqDYpTt9xTVODWX4p",
    "AVfgqDaITt9xTVODWX4t",
    "AVfgqDepTt9xTVODWX46",
    "AVfgqDgDTt9xTVODWX4-",
    "AVfgqDhHTt9xTVODWX5B",
    "AVfgqDh6Tt9xTVODWX5D",
    "AVfgqDlDTt9xTVODWX5L",
    "AVfgqDmvTt9xTVODWX5P",
    "AVfgqDqsTt9xTVODWX5b",
    "AVfgqDrdTt9xTVODWX5d",
    "AVfgqDsFTt9xTVODWX5f",
    "AVfgqDtzTt9xTVODWX5k",
    "AVfgqDu3Tt9xTVODWX5n",
    "AVfgqDvhTt9xTVODWX5p",
    "AVfgqDxiTt9xTVODWX5v",
    "AVfgqDySTt9xTVODWX5x",
    "AVfgqDzjTt9xTVODWX50",
    "AVfgqD0XTt9xTVODWX52",
    "AVfgqD3gTt9xTVODWX59",
    "AVfgqD50Tt9xTVODWX6E",
    "AVfgqD7ZTt9xTVODWX6I",
    "AVfgqD9GTt9xTVODWX6N",
    "AVfgqD9aTt9xTVODWX6O",
    "AVfgqD-KTt9xTVODWX6Q",
    "AVfgqD_fTt9xTVODWX6U",
    "AVfgqEBITt9xTVODWX6Z",
    "AVfgqEBcTt9xTVODWX6a",
    "AVfgqEC1Tt9xTVODWX6e",
    "AVfgqEDQTt9xTVODWX6f",
    "AVfgqEEATt9xTVODWX6h",
    "AVfgqEFvTt9xTVODWX6l",
    "AVfgqEIUTt9xTVODWX6r",
    "AVfgqEIqTt9xTVODWX6s",
    "AVfgqEJATt9xTVODWX6t",
    "AVfgqELUTt9xTVODWX60",
    "AVfgqEMPTt9xTVODWX63",
    "AVfgqESQTt9xTVODWX7J",
    "AVfgqEVqTt9xTVODWX7R",
    "AVfgqEXCTt9xTVODWX7V",
    "AVfgqEYrTt9xTVODWX7a",
    "AVfgqEapTt9xTVODWX7g",
    "AVfgqEcNTt9xTVODWX7l",
    "AVfgqEchTt9xTVODWX7m",
    "AVfgqEe8Tt9xTVODWX7t",
    "AVfgqEgUTt9xTVODWX7x",
    "AVfgqEgrTt9xTVODWX7y",
    "AVfgqDCbTt9xTVODWX3u",
    "AVfgqDFATt9xTVODWX30",
    "AVfgqDFcTt9xTVODWX31",
    "AVfgqDJLTt9xTVODWX3-",
    "AVfgqDJ1Tt9xTVODWX4A",
    "AVfgqDLeTt9xTVODWX4F",
    "AVfgqDOLTt9xTVODWX4N",
    "AVfgqDOiTt9xTVODWX4O",
    "AVfgqDU7Tt9xTVODWX4f",
    "AVfgqDVvTt9xTVODWX4h",
    "AVfgqDW3Tt9xTVODWX4k",
    "AVfgqDXjTt9xTVODWX4m",
    "AVfgqDYRTt9xTVODWX4o",
    "AVfgqDZYTt9xTVODWX4r",
    "AVfgqDafTt9xTVODWX4u",
    "AVfgqDbRTt9xTVODWX4w",
    "AVfgqDcOTt9xTVODWX4z",
    "AVfgqDciTt9xTVODWX40",
    "AVfgqDd8Tt9xTVODWX44",
    "AVfgqDjXTt9xTVODWX5H",
    "AVfgqDnZTt9xTVODWX5R",
    "AVfgqDtBTt9xTVODWX5i",
    "AVfgqDuOTt9xTVODWX5l",
    "AVfgqDujTt9xTVODWX5m",
    "AVfgqDvNTt9xTVODWX5o",
    "AVfgqDv1Tt9xTVODWX5q",
    "AVfgqDwKTt9xTVODWX5r",
    "AVfgqDx3Tt9xTVODWX5w",
    "AVfgqDzJTt9xTVODWX5z",
    "AVfgqD0DTt9xTVODWX51",
    "AVfgqD0tTt9xTVODWX53",
    "AVfgqD10Tt9xTVODWX55",
    "AVfgqD3LTt9xTVODWX58",
    "AVfgqD5gTt9xTVODWX6D",
    "AVfgqD6iTt9xTVODWX6G",
    "AVfgqD66Tt9xTVODWX6H",
    "AVfgqD8JTt9xTVODWX6K",
    "AVfgqD_HTt9xTVODWX6T",
    "AVfgqEBxTt9xTVODWX6b",
    "AVfgqEEbTt9xTVODWX6i",
    "AVfgqEE3Tt9xTVODWX6j",
    "AVfgqEJVTt9xTVODWX6u",
    "AVfgqEKTTt9xTVODWX6x",
    "AVfgqELoTt9xTVODWX61",
    "AVfgqEMrTt9xTVODWX64",
    "AVfgqEPkTt9xTVODWX7B",
    "AVfgqERpTt9xTVODWX7H",
    "AVfgqEWYTt9xTVODWX7T",
    "AVfgqEY_Tt9xTVODWX7b",
    "AVfgqEZ-Tt9xTVODWX7e",
    "AVfgqEdmTt9xTVODWX7p",
    "AVfgqEd6Tt9xTVODWX7q",
    "AVfgqEejTt9xTVODWX7s",
    "AVfgqEfPTt9xTVODWX7u",
    "AVfgqEhcTt9xTVODWX70",
    "AVfgqEjiTt9xTVODWX75",
    "AVfgqEj4Tt9xTVODWX76",
    "AVfgqEk6Tt9xTVODWX79",
    "AVfgqDBATt9xTVODWX3t",
    "AVfgqDDPTt9xTVODWX3w",
    "AVfgqDELTt9xTVODWX3y",
    "AVfgqDEmTt9xTVODWX3z",
    "AVfgqDIQTt9xTVODWX37",
    "AVfgqDKfTt9xTVODWX4C",
    "AVfgqDK0Tt9xTVODWX4D",
    "AVfgqDLJTt9xTVODWX4E",
    "AVfgqDMITt9xTVODWX4H",
    "AVfgqDNeTt9xTVODWX4L",
    "AVfgqDN1Tt9xTVODWX4M",
    "AVfgqDO4Tt9xTVODWX4P",
    "AVfgqDSDTt9xTVODWX4Y",
    "AVfgqDSaTt9xTVODWX4Z",
    "AVfgqDUMTt9xTVODWX4d",
    "AVfgqDWfTt9xTVODWX4j",
    "AVfgqDX9Tt9xTVODWX4n",
    "AVfgqDZwTt9xTVODWX4s",
    "AVfgqDeUTt9xTVODWX45",
    "AVfgqDfCTt9xTVODWX47",
    "AVfgqDfXTt9xTVODWX48",
    "AVfgqDftTt9xTVODWX49",
    "AVfgqDiyTt9xTVODWX5G",
    "AVfgqDl4Tt9xTVODWX5N",
    "AVfgqDmUTt9xTVODWX5O",
    "AVfgqDnvTt9xTVODWX5S",
    "AVfgqDobTt9xTVODWX5U",
    "AVfgqDowTt9xTVODWX5V",
    "AVfgqDpbTt9xTVODWX5X",
    "AVfgqDrBTt9xTVODWX5c",
    "AVfgqDrwTt9xTVODWX5e",
    "AVfgqDwfTt9xTVODWX5s",
    "AVfgqDxPTt9xTVODWX5u",
    "AVfgqDynTt9xTVODWX5y",
    "AVfgqD31Tt9xTVODWX5-",
    "AVfgqD4lTt9xTVODWX6A",
    "AVfgqD6JTt9xTVODWX6F",
    "AVfgqD8dTt9xTVODWX6L",
    "AVfgqD8yTt9xTVODWX6M",
    "AVfgqD-zTt9xTVODWX6S",
    "AVfgqEAGTt9xTVODWX6W",
    "AVfgqEAbTt9xTVODWX6X",
    "AVfgqECFTt9xTVODWX6c",
    "AVfgqECaTt9xTVODWX6d",
    "AVfgqEGGTt9xTVODWX6m",
    "AVfgqEL8Tt9xTVODWX62",
    "AVfgqEOSTt9xTVODWX69",
    "AVfgqEOqTt9xTVODWX6-",
    "AVfgqEPRTt9xTVODWX7A",
    "AVfgqEQXTt9xTVODWX7D",
    "AVfgqEQsTt9xTVODWX7E",
    "AVfgqERVTt9xTVODWX7G",
    "AVfgqETTTt9xTVODWX7M",
    "AVfgqEULTt9xTVODWX7O",
    "AVfgqEWDTt9xTVODWX7S",
    "AVfgqEXVTt9xTVODWX7W",
    "AVfgqEX-Tt9xTVODWX7Y",
    "AVfgqEZqTt9xTVODWX7d",
    "AVfgqEaTTt9xTVODWX7f",
    "AVfgqEa9Tt9xTVODWX7h",
    "AVfgqEhDTt9xTVODWX7z",
    "AVfgqEh4Tt9xTVODWX71",
    "AVfgqEi1Tt9xTVODWX73",
    "AVfgqEkOTt9xTVODWX77",
    "AVfgqDC0Tt9xTVODWX3v",
    "AVfgqDDsTt9xTVODWX3x",
    "AVfgqDG0Tt9xTVODWX33",
    "AVfgqDHnTt9xTVODWX35",
    "AVfgqDMyTt9xTVODWX4J",
    "AVfgqDQ7Tt9xTVODWX4V",
    "AVfgqDRpTt9xTVODWX4X",
    "AVfgqDTUTt9xTVODWX4b",
    "AVfgqDT3Tt9xTVODWX4c",
    "AVfgqDXMTt9xTVODWX4l",
    "AVfgqDZBTt9xTVODWX4q",
    "AVfgqDc9Tt9xTVODWX41",
    "AVfgqDdmTt9xTVODWX43",
    "AVfgqDgyTt9xTVODWX5A",
    "AVfgqDiOTt9xTVODWX5E",
    "AVfgqDihTt9xTVODWX5F",
    "AVfgqDj6Tt9xTVODWX5I",
    "AVfgqDklTt9xTVODWX5K",
    "AVfgqDlhTt9xTVODWX5M",
    "AVfgqDoDTt9xTVODWX5T",
    "AVfgqDpFTt9xTVODWX5W",
    "AVfgqDpwTt9xTVODWX5Y",
    "AVfgqDsZTt9xTVODWX5g",
    "AVfgqD1KTt9xTVODWX54",
    "AVfgqD2YTt9xTVODWX56",
    "AVfgqD2wTt9xTVODWX57",
    "AVfgqD43Tt9xTVODWX6B",
    "AVfgqD_zTt9xTVODWX6V",
    "AVfgqEDnTt9xTVODWX6g",
    "AVfgqEFLTt9xTVODWX6k",
    "AVfgqEHBTt9xTVODWX6o",
    "AVfgqEHcTt9xTVODWX6p",
    "AVfgqEJ_Tt9xTVODWX6w",
    "AVfgqEKnTt9xTVODWX6y",
    "AVfgqELBTt9xTVODWX6z",
    "AVfgqEM-Tt9xTVODWX65",
    "AVfgqENRTt9xTVODWX66",
    "AVfgqENkTt9xTVODWX67",
    "AVfgqEP9Tt9xTVODWX7C",
    "AVfgqERATt9xTVODWX7F",
    "AVfgqESsTt9xTVODWX7K",
    "AVfgqES_Tt9xTVODWX7L",
    "AVfgqET2Tt9xTVODWX7N",
    "AVfgqEVITt9xTVODWX7Q",
    "AVfgqEWtTt9xTVODWX7U",
    "AVfgqEYTTt9xTVODWX7Z",
    "AVfgqEeOTt9xTVODWX7r",
    "AVfgqEieTt9xTVODWX72",
    "AVfgqEjITt9xTVODWX74",
    "AVfgqEknTt9xTVODWX78"
  )

  //no need secure random due to the network and update time cost
  val r = new Random

  private def format(n: Int): String = f"$n%2d"

  private def wrapScore(s: String): String = s"[ $s ] "

  private def makeReadable(n: Int): String =
    if (n > 0)      s"${AnsiColor.GREEN + format(n) + AnsiColor.RESET}"
    else if (n < 0) s"${AnsiColor.RED   + format(n) + AnsiColor.RESET}"
    else            s"${format(n)}"
 
 //show pretty
  private def makeReadable(s: String): String =
    s.takeWhile(_ != '\n').take(80) + "..."

  def makeReadable(sn: (String, Int)): String =
    sn match {
      case (tweetText, score) => {
        ESUtil.upMethod1(ids(r.nextInt(ids.length-1)),tweetText)
        s"${wrapScore(makeReadable(score))}${makeReadable(tweetText)}"
      }
    }


}
